apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysqldb
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306       # The port that the service will expose
      targetPort: 3306 # The port on the container
  type: ClusterIP
