apiVersion: v1
kind: Service
metadata:
  name: spring-kube-service
spec:
  selector:
    app: spring-kube-app
  ports:
    - protocol: TCP
      port: 9090   # Port to expose on the service
      targetPort: 8089  # Port your application is listening on in the container
  type: NodePort  # Expose the service on a node port
